[0m[[0m[31merror[0m] [0m[0m/Users/ericohwotu/Development/hmrc-development-environment/ddct/va-sa20/some-test/src/test/scala/FutureFunctorSpec.scala:28:36: type mismatch;[0m
[0m[[0m[31merror[0m] [0m[0m found   : Unit[0m
[0m[[0m[31merror[0m] [0m[0m required: scala.concurrent.Future[org.scalatest.compatible.Assertion][0m
[0m[[0m[31merror[0m] [0m[0m    } yield thirdCall).item.foreach{[0m
[0m[[0m[31merror[0m] [0m[0m                                   ^[0m
[0m[[0m[31merror[0m] [0m[0m/Users/ericohwotu/Development/hmrc-development-environment/ddct/va-sa20/some-test/src/test/scala/FutureFunctorSpec.scala:34:62: type mismatch;[0m
[0m[[0m[31merror[0m] [0m[0m found   : Unit[0m
[0m[[0m[31merror[0m] [0m[0m required: scala.concurrent.Future[org.scalatest.compatible.Assertion][0m
[0m[[0m[31merror[0m] [0m[0m  it must "stop at the first Option.empty[T] experienced" in {[0m
[0m[[0m[31merror[0m] [0m[0m                                                             ^[0m
[0m[[0m[31merror[0m] [0m[0mtwo errors found[0m
